export const API_URL = 'http://localhost:5000/api/v1';
export const ACCESS_TOKEN = 'ACCESS_TOKEN';

export const FULLNAME_MIN_LENGTH = 3;
export const FULLNAME_MAX_LENGTH = 60;

export const USERNAME_MIN_LENGTH = 3;
export const USERNAME_MAX_LENGTH = 40;

export const EMAIL_MAX_LENGTH = 60;

export const PASSWORD_MIN_LENGTH = 8;
export const PASSWORD_MAX_LENGTH = 100;

export const AGENT_DESCRIPTION_MIN_LENGTH = 1;
export const AGENT_DESCRIPTION_MAX_LENGTH = 200;
export const AGENT_NAME_MAX_LENGTH = 60;
export const AGENT_NAME_MIN_LENGTH = 3;
export const AGENT_ALLOWED_ORIGINS_MAX_LENGTH = 200;

export const AGENT_SERVICE_DESCRIPTION_MIN_LENGTH = 1;
export const AGENT_SERVICE_DESCRIPTION_MAX_LENGTH = 300;
export const AGENT_SERVICE_NAME_MAX_LENGTH = 100;
export const AGENT_SERVICE_NAME_MIN_LENGTH = 1;

export const AGENT_MONITORING_PARAMETER_DESCRIPTION_MIN_LENGTH = 1;
export const AGENT_MONITORING_PARAMETER_DESCRIPTION_MAX_LENGTH = 200;

export const AGENT_LIST_SIZE = 10;
export const AGENT_SERVICES_LIST_SIZE = 5;
export const AGENT_SERVICES_CONFIGURATION_LIST_SIZE = 5;

export const INDEX_PAGE_SIZE_DEFAULT = 50;
export const INDEX_PAGE_SIZE_OPTIONS = [5, 10, 20, 30, 50, 100];

export const LOGS_LIST_SIZE = 100;

export const USER_LIST_SIZE = 50;
export const ALERTS_LIST_SIZE = 10;

export const ALERT_MESSAGE_MIN_LENGTH = 3;
export const ALERT_MESSAGE_MAX_LENGTH = 200;
export const LOGS_ALERT_SEARCH_STRING_MAX_LENGTH = 200;
export const MONITORING_ALERT_VALUE_MIN_LENGTH = 1;
export const MONITORING_ALERT_VALUE_MAX_LENGTH = 200;
export const ALERTS_CONFIGS_LIST_SIZE = 20;



