server:
  port: 8443
  compression:
    enabled: true # Enable response compression
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json # The comma-separated list of mime types that should be compressed
    min-response-size: 1024 # Compress the response only if the response size is at least 1KB
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store-password: HiVKZRjC3ma
    key-password: HiVKZRjC3ma
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS

spring:
  security:
    ignored: /**
  datasource:
    driverClassName: org.postgresql.Driver
    initialization-mode: always # Initialize the datasource with available DDL and DML scripts
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      fail-on-empty-beans: false # TODO(low): fix it, some clues https://stackoverflow.com/questions/24994440/no-serializer-found-for-class-org-hibernate-proxy-pojo-javassist-javassist
    time-zone: UTC
  jpa:
    properties:
      #hibernate: temp.use_jdbc_metadata_defaults=false # Disable feature detection by this undocumented parameter. Check the org.hibernate.engine.jdbc.internal.JdbcServiceImpl.configure method for more details.
      hibernate:
        jdbc:
          time_zone: Europe/Warsaw
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect # Because detection is disabled you have to set correct dialect by hand.
    hibernate:
      ddl-auto: update # The SQL dialect makes Hibernate generate better SQL for the chosen database
  mvc:
    logResolvedException: false
app:
  jwtExpirationInMs: 600000
  clientURL: @client.server.address@
  clientPasswordResetCallback: password/confirm/reset
  clientUserActivationCallback: user/activate
  # 3 values below are used for CORS
  CORSAllowAll: false               
  apiUri: /api/v1
  apiWebServiceUri: /service/api/v1
  enableSwagger: true
  mail:
    appServerAddress: @app.server.address@


logging:
  level:
    root: ERROR
    org:
      hibernate:
        SQL: ERROR
    pdm:
      networkservicesmonitor: INFO
  file: ../log/NSM.log


