server:
  port: 9999
agent:
  monitor:
    address: @monitor.ip@
    port: @monitor.port@
    api:
      uri: service/api/v1
      webserviceednpoint: agent/webservice
  id: @agent.id@
  encryptionKey: @agent.encryptionKey@
app:
  temporary:
    directory: tmp
  jwtExpirationInMs: 600000
  apiUri: /service/api/v1

logging:
  level:
    root: INFO
    pdm:
      networkservicesmonitor: TRACE
  file: /var/log/agent/NSM_agent.log


