server:
  port: 9999
  ssl:
    key-alias: selfsigned_localhost_sslserver
    key-store-password: HiVKZRjC3ma
    key-password: HiVKZRjC3ma
    key-store: classpath:ssl-server.jks
    key-store-provider: SUN
    key-store-type: JKS

agent:
  monitor:
    address: @monitor.ip@
    port: @monitor.port@
    api:
      uri: service/api/v1
      webserviceednpoint: agent/webservice
  id: @agent.id@
  encryptionKey: @agent.encryptionKey@
  ssl:
    validation:
      enabled: false
app:
  temporary:
    directory: tmp
  jwtExpirationInMs: 600000
  apiUri: /service/api/v1

logging:
  level:
    root: INFO
    pdm:
      networkservicesmonitor: TRACE
  file: /var/log/agent/NSM_agent.log

appdynamics:
  force:
    default:
      ssl:
        certificate:
          validation: false


